/* Auto-generated by genmsg_cpp for file /Users/rimesime/ros/fu_tools/waypoint/srv/MarkWaypoint.srv */
#ifndef WAYPOINT_SERVICE_MARKWAYPOINT_H
#define WAYPOINT_SERVICE_MARKWAYPOINT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "ros/service_traits.h"




namespace waypoint
{
template <class ContainerAllocator>
struct MarkWaypointRequest_ : public ros::Message
{
  typedef MarkWaypointRequest_<ContainerAllocator> Type;

  MarkWaypointRequest_()
  {
  }

  MarkWaypointRequest_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "waypoint/MarkWaypointRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::waypoint::MarkWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint::MarkWaypointRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct MarkWaypointRequest
typedef  ::waypoint::MarkWaypointRequest_<std::allocator<void> > MarkWaypointRequest;

typedef boost::shared_ptr< ::waypoint::MarkWaypointRequest> MarkWaypointRequestPtr;
typedef boost::shared_ptr< ::waypoint::MarkWaypointRequest const> MarkWaypointRequestConstPtr;


template <class ContainerAllocator>
struct MarkWaypointResponse_ : public ros::Message
{
  typedef MarkWaypointResponse_<ContainerAllocator> Type;

  MarkWaypointResponse_()
  {
  }

  MarkWaypointResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "waypoint/MarkWaypointResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::waypoint::MarkWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint::MarkWaypointResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct MarkWaypointResponse
typedef  ::waypoint::MarkWaypointResponse_<std::allocator<void> > MarkWaypointResponse;

typedef boost::shared_ptr< ::waypoint::MarkWaypointResponse> MarkWaypointResponsePtr;
typedef boost::shared_ptr< ::waypoint::MarkWaypointResponse const> MarkWaypointResponseConstPtr;

struct MarkWaypoint
{

typedef MarkWaypointRequest Request;
typedef MarkWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct MarkWaypoint
} // namespace waypoint

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::waypoint::MarkWaypointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::waypoint::MarkWaypointRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint::MarkWaypointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "waypoint/MarkWaypointRequest";
  }

  static const char* value(const  ::waypoint::MarkWaypointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::waypoint::MarkWaypointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::waypoint::MarkWaypointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::waypoint::MarkWaypointRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::waypoint::MarkWaypointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::waypoint::MarkWaypointResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint::MarkWaypointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "waypoint/MarkWaypointResponse";
  }

  static const char* value(const  ::waypoint::MarkWaypointResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::waypoint::MarkWaypointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::waypoint::MarkWaypointResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::waypoint::MarkWaypointResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::waypoint::MarkWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MarkWaypointRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::waypoint::MarkWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MarkWaypointResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<waypoint::MarkWaypoint> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const waypoint::MarkWaypoint&) { return value(); } 
};

template<>
struct DataType<waypoint::MarkWaypoint> {
  static const char* value() 
  {
    return "waypoint/MarkWaypoint";
  }

  static const char* value(const waypoint::MarkWaypoint&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<waypoint::MarkWaypointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const waypoint::MarkWaypointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<waypoint::MarkWaypointRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "waypoint/MarkWaypoint";
  }

  static const char* value(const waypoint::MarkWaypointRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<waypoint::MarkWaypointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const waypoint::MarkWaypointResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<waypoint::MarkWaypointResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "waypoint/MarkWaypoint";
  }

  static const char* value(const waypoint::MarkWaypointResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // WAYPOINT_SERVICE_MARKWAYPOINT_H

